// Auto-generated by generate-tier0-persons.ts — do not edit manually
// Run: npx tsx scripts/pipeline/generate-tier0-persons.ts
import type { AIPersonMention } from "./ai-analyzer";

export const GENERATED_TIER0_PERSONS: [string, string, AIPersonMention["category"]][] = [];
